// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import (
	"database/sql"
)

type User struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	DateOfBirth sql.NullTime   `json:"date_of_birth"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	Description sql.NullString `json:"description"`
}
